t1 = ("appel", "mango","banaan",1,("geel","groen"))
print( type( t1 ) )
t2 = "banaan", "kers",1,1.0,"1",("geel","groen")
print( type( t2 ) )
print (len(t1))
print(t2)
print(len(t2))
t1 = (327, 419, 101, 667, 925, 225)
print( max( t1 ) )
print( min( t1 ) )
print( sum( t1 ) )
t1 = ("appel", "banaan", "kers")
print( "banaan" in t1 )
print( "mango" in t1 )
t1 = "appel","peer"
print(type(t1))
t1, t2 = "appel", "banaan"
print( t1 )
print( t2 )
